#!/bin/bash

echo "starting mediamtx on localhost:8554"
docker rm -f mediamtx
docker run -d \
  --restart unless-stopped \
  --network=host \
  --privileged \
  --tmpfs /dev/shm:exec \
  --name mediamtx \
  -v /home/hellmann/onvif/mediamtx.yml:/mediamtx.yml:ro \
  bluenviron/mediamtx:latest-ffmpeg-rpi

sleep 5

echo "starting onvif-server advertising on :554"
pushd /home/hellmann/onvif/onvif-server
node main.js ./config.yaml
popd

echo "reached eof"
